# Generated by Django 5.2 on 2025-05-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Sphere'), ('2', 'Cylinder'), ('3', 'Cube')], max_length=1)),
                ('colour', models.CharField(max_length=7)),
            ],
        ),
    ]
